spring_bookshop/src/com/liaoyu/web/book/BookAction.java
package com.liaoyu.web.book;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.imageio.ImageIO;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.io.FileUtils;
import org.apache.struts2.ServletActionContext;
import org.apache.struts2.interceptor.SessionAware;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.liaoyu.bean.book.Book;
import com.liaoyu.bean.user.User;
import com.liaoyu.service.book.BookService;
import com.liaoyu.service.book.BookTypeService;
import com.liaoyu.utils.ImageUtil;
import com.liaoyu.utils.StringUtils;
import com.liaoyu.web.BaseAction;
import com.opensymphony.xwork2.ActionContext;
import com.opensymphony.xwork2.ModelDriven;
import com.opensymphony.xwork2.Preparable;

@Controller	@Scope("prototype")
public class BookAction  extends BaseAction  implements Preparable,ModelDriven<Book>,SessionAware{
	private static final long serialVersionUID = 1L;
	@Resource BookService bs;
	@Resource BookTypeService bts;
	Book book=new Book();
	private String btype;
	private String stype;
	private File bimage;
	private String bimageFileName;
	private String bimageContentType;
	private String nextPage;
	private String item[];
	Map<String, Object> session=new HashMap<String, Object>();
	PrintWriter out=null;
	
	@Override
	public void prepare() throws Exception {
		out=getResponse().getWriter();
	}
	@Override
	public void setSession(Map<String, Object> session) {
		this.session=session;
	}
	public String getBimageContentType() {
		return bimageContentType;
	}
	public void setBimageContentType(String bimageContentType) {
		this.bimageContentType = bimageContentType;
	}
	public String[] getItem() {
		return item;
	}
	public void setItem(String[] item) {
		this.item = item;
	}
	public String getNextPage() {
		return nextPage;
	}
	public void setNextPage(String nextPage) {
		this.nextPage = nextPage;
	}
	public File getBimage() {
		return bimage;
	}
	public void setBimage(File bimage) {
		this.bimage = bimage;
	}
	public String getBimageFileName() {
		return bimageFileName;
	}
	public void setBimageFileName(String bimageFileName) {
		this.bimageFileName = bimageFileName;
	}
	public Book getBook() {
		return book;
	}
	public void setBook(Book book) {
		this.book = book;
	}
	@Override
	public Book getModel() {
		return book;
	}
	public String getStype() {
		return stype;
	}
	public void setStype(String stype) {
		this.stype = stype;
	}
	public String getBtype() {
		return btype;
	}
	public void setBtype(String btype) {
		this.btype = btype;
	}
	
	public String addBook(){
		this.clearMessages();
		try {
			boolean flag = UploadImage();
			//往数据库增添数据
			if(flag)bs.addBook(book, btype, stype);
			else bs.addBookByNewType(book, btype, stype);
		} catch (IOException e) {
			e.printStackTrace();
			setNextPage("/admin/addBook.jsp");
			this.addActionMessage("保存失败！");
			return ERROR;
		}
		setNextPage("/admin/addBook.jsp");
		this.addActionMessage("保存成功！");
		return SUCCESS;
	}
	
	public String editBook(){
		this.clearMessages();
		try {
			boolean flag = UploadImage();
			//往数据库增添数据
			if(flag)bs.updateBook(book, btype, stype);
			else bs.updateBookByNewType(book, btype, stype);
		} catch (IOException e) {
			e.printStackTrace();
			setNextPage("/admin/message.jsp");
			this.addActionMessage("保存失败！");
			return ERROR;
		}
		setNextPage("/showBook.do");
		this.addActionMessage("保存成功！");
		return "toAction";
	}
	public String deleteBook(){
		if(item!=null&&item.length>0){
			try {
				for(String num:item)
					bs.delete(Integer.parseInt(num));
			} catch (NumberFormatException e) {
				this.addActionMessage("对不起，出错啦");
				setNextPage("/share/message.jsp");
				return "error";
			}
			this.addActionMessage("删除成功");
			setNextPage("/showBook.do");
			return "toAction";
		}
		else{
			this.addActionMessage("对不起，出错啦");
			setNextPage("/share/message.jsp");
			return "error";
		}
	}
	public String searchBook(){
		book=bs.find(book.getBid());
		setNextPage("/admin/editBook.jsp");
		return SUCCESS;
	}
	public String getBookInfo(){
		Book nowBook=bs.find(book.getBid());
		ActionContext.getContext().put("bookDetail", nowBook);
		setNextPage("/user/add_comment.jsp");
		return SUCCESS;
	}
	private boolean UploadImage() throws IOException {
		if(bimage!=null){
			//获取上传路径
			String realPath=ServletActionContext.getServletContext().getRealPath("/upload/book/images");
			//获取扩展名
			String fileExt=this.bimageFileName.substring(this.bimageFileName.lastIndexOf("."), this.bimageFileName.length());
			//产生文件名
			String baseName=StringUtils.getRandomName();
			File savefile=new File(new File(realPath),baseName+ fileExt);
			File savefilemini=new File(new File(realPath),baseName+"mini"+ fileExt);
			//判断是否存在保存目录，否则创建
			if(!savefile.getParentFile().exists())savefile.getParentFile().mkdirs();
			//用FileUtils工具上传文件
			FileUtils.copyFile(bimage,savefile);
			//产生缩略图
			ImageUtil.zoom(ImageIO.read(bimage),savefilemini,120,120);
			//进行注册
			book.setImage(baseName+ fileExt);
		}
		//判断图书类型是否存在
		boolean flag=bts.exists(btype, stype);
		return flag;
	}
	public String searchById(){
		Book resultBook=bs.find(book.getBid());
		if(resultBook==null){
			addActionMessage("404，抱歉求找到该商品");
			setNextPage("/share/message.jsp");
			return "error";
		}else{
			ActionContext.getContext().put("resultBook", resultBook);
			setNextPage("/product/pdetails.jsp");
			//为浏览记录写入Cookie
			Cookie cookie=new Cookie("visited_bid", resultBook.getBid()+"");
			cookie.setMaxAge(60*60*24);	//一天
			//热门图书
			ActionContext.getContext().put("bestSellerBooks",bs.getBestSellerBook(4).getResultlist());
			//类型相似的图书
			ActionContext.getContext().put("sameTypeBooks",bs.getSameTypeBook(resultBook.getBookType().getTypeId()));
			//操作Cookie 关于最近浏览过的图书
			HttpServletRequest request=ServletActionContext.getRequest();
			HttpServletResponse response=ServletActionContext.getResponse();
			ActionContext.getContext().put("haveScanBooks",getHaveScanBook(request,response,book.getBid()));
			return SUCCESS;
		}
	}
	//通过cookie返回浏览过的图书 
	private List getHaveScanBook(HttpServletRequest request,HttpServletResponse response,int bid) {
		Cookie[] cookies=request.getCookies();
		List books=new ArrayList();
		if(cookies!=null&&cookies.length>0){
			StringBuffer bidValue=new StringBuffer("");
			int count=0;
			for(Cookie cookie:cookies){
				if("scanbid".equals(cookie.getName())){		//判断是否存在cookie
					++count;
					bidValue.append(cookie.getValue());		//获取当前的cookie
				}
			}
			//获取cookie中已经存在的值
			if(bidValue.length()>0){
				String [] bidArray=bidValue.toString().split("_");
				//限定返回的数量
				for(int k=0;k<bidArray.length&&k<4;k++){
					books.add(bs.find(Integer.valueOf(bidArray[bidArray.length-k-1])));
				}
			}
			//返回客户端的cookie操作
			if(count==0){
				response.addCookie(new Cookie("scanbid", bid+""));
			}else{
				//判断是否存在同ID的图书
				boolean flag=false;
				for(String strItem:bidValue.toString().split("_")){
					if((""+bid).equals(strItem)){
						flag=true;
					}
				}
				if(!flag){
					bidValue.append("_"+bid);
				}
				response.addCookie(new Cookie("scanbid", bidValue.toString()));
			}
		}
		return books;
	}
	public String addCollect(){
		User user=(User) session.get("user");
		PrintWriter out=null;
		try {
			out=ServletActionContext.getResponse().getWriter();
		} catch (IOException e) {
			e.printStackTrace();
		}
		if(user!=null){
			int uid=user.getUid();
			int bid=book.getBid();
			if(bid>0){
				boolean flag=bs.addCollectBook(bid, uid);
				if(!flag){
					out.print("收藏失败！");
					out.close();
					return null;
				}
				//修改图书收藏数量
				Book collectBook=bs.find(bid);
				collectBook.setCollectCount(collectBook.getCollectCount()+1);
				bs.update(collectBook);
				out.print("收藏成功！");
				out.close();
				return SUCCESS;
			}else{
				out.print("请选择要收藏的图书！");
				out.close();
				return null;
			}
		}else{
			out.print("对不起，您尚未登录！");
			out.close();
			return null;
		}
		
	}
	//获取已收藏的图书
	public String getCollect(){
		User user=(User) session.get("user");
		if(user==null){
			out.print("<script>window.history.back();alert('请先登录！');</script>");
			return null;
		}
		List<Book> books=bs.getCollectBook(user.getUid());
		ActionContext.getContext().put("collectBooks", books);
		return "toCollectBookPage";
	}

}

spring_bookshop/WebContent/product/pdetails.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core"  prefix="c"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>优优图书</title>
<script type="text/javascript" src="${pageContext.request.contextPath }/js/jquery-1.8.3.js" ></script>
<script src="${pageContext.request.contextPath }/js/jquery.hashchange.min.js" type="text/javascript"></script>
<script src="${pageContext.request.contextPath }/js/jquery.easytabs.min.js" type="text/javascript"></script>
<script type="text/javascript" src="${pageContext.request.contextPath }/js/global.js" ></script>
<script type="text/javascript" src="${pageContext.request.contextPath }/js/pdetails.js" ></script>
<link  rel="stylesheet" href="${pageContext.request.contextPath }/css/global.css" />
<link  rel="stylesheet" href="${pageContext.request.contextPath }/css/pdetails.css" />
</head>
<body>
<div class="msg2 curved"><ul><li>保存成功！</li></ul></div>
<%@include file="/share/header.jsp" %>

<div class="content">

<div class="breadcrumb" >
<a href="#" target="_blank" class="domain"><b class="domain">图书</b></a>&nbsp;&gt;&nbsp;
<a href="#" target="_blank">古籍</a>&nbsp;&gt;&nbsp;
<span>商品详情</span>
</div>

<div class="content_left">

<div class="all_div">
<p class="all_title">浏览本商品的顾客还看过</p>
<div class="all_content">
<div class="reBooks">
<ul>
<c:forEach var="book" items="${requestScope.sameTypeBooks }">
	<li>
		<a class="pic1" href="${pageContext.request.contextPath }/book_searchById.do?bid=${book.bid }"><img src="/spring_bookshop/upload/book/images/${book.image }"  title="${book.bname }" width="54px" height="54px"/></a>
		<a class="bookName" href="${pageContext.request.contextPath }/book_searchById.do?bid=${book.bid }">${book.bname }</a>
		<span class="d_price">¥${book.price }</span>
	</li>
</c:forEach>
</ul>
</div>
</div>
</div>

<div class="all_div">
<p class="all_title">您的浏览历史</p>
<div class="all_content">
<div class="reBooks">
<ul>
<c:forEach var="book" items="${requestScope.haveScanBooks }">
	<li>
		<a class="pic1" href="${pageContext.request.contextPath }/book_searchById.do?bid=${book.bid }"><img src="/spring_bookshop/upload/book/images/${book.image }"  title="${book.bname }" width="54px" height="54px"/></a>
		<a class="bookName" href="${pageContext.request.contextPath }/book_searchById.do?bid=${book.bid }">${book.bname }</a>
		<span class="d_price">¥${book.price }</span>
	</li>
</c:forEach>
</ul>
</div>
</div>
</div>

<div class="all_div">
<p class="all_title">热卖图书</p>
<div class="all_content">
<div class="reBooks">
<ul>
<c:forEach var="book" items="${requestScope.bestSellerBooks }">
	<li>
		<a class="pic1" href="${pageContext.request.contextPath }/book_searchById.do?bid=${book.bid }"><img src="/spring_bookshop/upload/book/images/${book.image }"  title="${book.bname }" width="54px" height="54px"/></a>
		<a class="bookName" href="${pageContext.request.contextPath }/book_searchById.do?bid=${book.bid }">${book.bname }</a>
		<span class="d_price">¥${book.price }</span>
	</li>
</c:forEach>
</ul>
</div>
</div>
</div>
</div>

<div class="content_right">
<p class="bookTitle">${resultBook.bname}</p>
<div class="showPic">
<div class="big"><a href="#"><img id="book_image" src="${pageContext.request.contextPath }/upload/book/images/${resultBook.image}" width="350" height="350"/></a></div>
</div>
<div class="bookDetails">
<p>商品编号：<uumark class="book_id">${resultBook.bid}</uumark></p>
<p>优 优 价：<b class="b_price item_price">¥${resultBook.price}</b></p>
<p>丛 书 名：尚无消息</p>
<p>作 者：${resultBook.author}</p>
<p>出 版 社：${resultBook.publishCompany}</p>
<p>出版时间：${resultBook.publishDate}</p>
<p><span>版　　次：1</span><span>页　　数：2160</span><span>字　　数：386000</span></p>
<p><span>印刷时间：2009-10-1</span><span>开　　本：64开</span><span>纸　　张：胶版纸</span></p>
<p><span>印　　次：1</span><span>I S B N：23229473</span><span>包　　装：精装</span></p>
<div class="clear"></div>
<div class="buy_area">
<p class="wannaBuy">我要买：
            <a href="javascript:void(0);" class="cut a_mini" title="数量减一" onclick="reductCount()"></a>
            <input type="text"  class="input_mini" value="1" disabled="disabled"/>
            <a href="javascript:void(0);" class="add a_mini" title="数量加一" onclick="addCount()"></a>
            <span class="allCount">总额为：<b class="b_price allPrice">¥${resultBook.price}</b></span>
</p>
<div class="btn_p">
<a href="javascript:void(0);" class="btn btn_buy" title="购买" id="part_buy_button" onclick="buyBook()"></a>
<a href="javascript:void(0);"  id="collect" title="收藏" class="btn btn_collect" onclick="addCollect()"></a>
</div>
</div>
</div>

<div class="clear"></div>
<div class="bunket">
<h3>购买本商品的顾客还买过</h3>
<div class="over">
<ul id="targetUL">
<li>
<a href="#"><img src="${pageContext.request.contextPath }/images/default2.jpg" width="150" height="150"/></a>
<p><a href="#">套装（全六册）</a></p>
<p class="d_price">¥30.00</p>
</li>
<li>
<a href="#"><img src="${pageContext.request.contextPath }/images/author6.jpg" width="150" height="150"/></a>
<p><a href="#">套装（全六册）</a></p>
<p class="d_price">¥30.00</p>
</li>
<li>
<a href="#"><img src="${pageContext.request.contextPath }/images/default7.jpg" width="150" height="150"/></a>
<p><a href="#">套装（全六册）</a></p>
<p class="d_price">¥30.00</p>
</li>
<li>
<a href="#"><img src="${pageContext.request.contextPath }/images/default2.jpg" width="150" height="150"/></a>
<p><a href="#">套装（全六册）</a></p>
<p class="d_price">¥30.00</p>
</li>
<li>
<a href="#"><img src="${pageContext.request.contextPath }/images/author5.jpg" width="150" height="150"/></a>
<p><a href="#">套装（全六册）</a></p>
<p class="d_price">¥30.00</p>
</li>

</ul>
</div>
<a id="a_alsobuy_pic_pre" class="btn_a prev_none" style="display:block;"><span class="btn"></span></a>
<a id="alsobuy_pic_next"  class="btn_a next_none" style="display:block;"><span class="btn"></span></a>
</div>
<div class="tab_re">
<div id="tab-other" class="tab-other">
  <ul class='etabs'>
    <li class='tab'><a href="#tabs-detail">图书详情</a></li>
    <li class='tab'><a href="#tabs-commend">图书评价</a></li>
    <li class='tab'><a href="#tabs-dis">图书讨论</a></li>
  </ul>
  <div id="tabs-detail">
    <div class="b_detail">${resultBook.bookInfo}</div>
  </div>
  <div id="tabs-commend">
    <div class="b_detail">
    <c:forEach var="comment" items="${resultBook.comments }">
    	<div class="comment">
    		<div class="pl_photo">
    			<p><img src="/spring_bookshop/upload/user/images/${comment.user.photo }"  width="60px" height="60px"/></p>
    			<p class="name">${comment.user.nickname }</p>
    		</div>
    		<div class="title_top">非常喜欢</div>
    		<div class="title">
    			<span class="level">发表于${comment.pdate }</span>
    			<span class="starlevel s5"></span>
    			<span class="time">购买于${comment.bdate }</span>
    		</div>
    		<div class="clear"></div>
    		<div class="s_cont">${comment.content }</div>
    		<div class="operation"><a href="#"><span>赞</span></a><a href="#" class="icon_hf"><span>回复</span></a></div>
    	</div>
    	</c:forEach>
    </div>
  </div>
  <div id="tabs-dis">
     <div class="b_detail"></div>
  </div>
</div>
</div>
</div>

</div>

<jsp:include page="../share/footer.jsp" />
<script type="text/javascript">
$(function(){
	//设置评论边框
	$('.b_detail .comment:last').css('border-bottom','none');
	//购买本商品的顾客还买过  翻页动画
	$('#a_alsobuy_pic_pre').click(function(){
		var marginLeft=$('#targetUL').css('margin-left');
		if(eval(marginLeft.replace(/px/i,''))==0)return;
		$('#targetUL').animate({'margin-left':(eval(marginLeft.replace(/px/i,''))+168)+'px'});
	});
	$('#alsobuy_pic_next').click(function(){
		var marginLeft=$('#targetUL').css('margin-left');
		$('#targetUL').animate({'margin-left':(eval(marginLeft.replace(/px/i,''))-168)+'px'});
	});
});
</script>
</body>
</html>